global_defs {
  router_id haproxy01
  vrrp_garp_interval 0
  vrrp_gna_interval 0
}

vrrp_script chk_haproxy {
  script "pidof haproxy"
  interval 2
  weight -5
  fall 2
  rise 1
}

vrrp_instance VI_1 {
  state MASTER
  interface ens33
  virtual_router_id 51
  priority 110
  advert_int 1

  authentication {
    auth_type PASS
    auth_pass REDACTED
  }

  unicast_src_ip 192.168.152.5
  unicast_peer {
    192.168.152.6
  }

  track_script {
    chk_haproxy
  }

  virtual_ipaddress {
    192.168.152.7/24
  }

  notify_master "/usr/local/bin/haproxy-start.sh"
  notify_backup "/usr/local/bin/haproxy-stop.sh"
  notify_fault  "/usr/local/bin/haproxy-stop.sh"
}

