vrrp_instance piholeHA {
  state BACKUP
  interface eth0

  unicast_src_ip 192.168.100.3
  unicast_peer {
    192.168.100.2
  }

  virtual_router_id 1 
  priority 9 
  advert_int 1

  authentication {
    auth_type PASS
    auth_pass REDACTED#
  }

  virtual_ipaddress {
    192.168.100.4/24
  }
}

